services:
  amor-segb:
    container_name: amor-segb-flask
    image: ghcr.io/gsi-upm/amor-segb:0.2.0
    ports:
      - "5000:5000"
    networks:
      - internal_network
    depends_on:
      - amor-segb-mongodb
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1

  amor-segb-mongodb:
    container_name: amor-segb-mongodb
    image: mongodb/mongodb-community-server:8.0.0-ubi8
    volumes:
      - amor-segb-db:/data/db
      - amor-segb-db:/data/configdb
    networks:
      - internal_network
    

networks:
  internal_network:
    driver: bridge

volumes:
  amor-segb-db: