version: '3.8'

services:
  flask:
    build: ./flask
    ports:
      - "5000:5000"
    volumes:
      - ./flask/app:/app
    networks:
      - internal_network  
    depends_on:
      - mongodb
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1

  mongodb:
    image: mongodb/mongodb-community-server:8.0.0-ubi8
    volumes:
      - db:/data/db
      - db:/data/configdb
    networks:
      - internal_network
    command: ["mongod"]
    ports:
      - "27017:27017"
    

networks:
  internal_network:
    driver: bridge 

volumes:
  db:
