services:
  sebb:
    container_name: amor-sebb
    image: ghcr.io/gsi-upm/amor-sebb:latest
    ports:
      - "5000:5000"
    networks:
      - internal_network
    depends_on:
      - mongodb
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1

  mongodb:
    container_name: amor-sebb-mongodb
    image: mongodb/mongodb-community-server:8.0.0-ubi8
    volumes:
      - db:/data/db
      - db:/data/configdb
    networks:
      - internal_network
    ports:
      - "27017:27017"
    

networks:
  internal_network:
    driver: bridge

volumes:
  db: