services:
  amor-segb:
    container_name: amor-segb-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - internal_network
    depends_on:
      - amor-segb-mongodb
      - amor-segb-neo4j
    env_file:
      - ./.env
    volumes:
      - ./logs:/logs
    links:
      - "amor-segb-mongodb:database"
      - "amor-segb-neo4j:graph"

  amor-segb-mongodb:
    container_name: amor-segb-mongodb
    image: mongodb/mongodb-community-server:8.0.0-ubi8
    volumes:
      - amor-segb-db:/data/db
      - amor-segb-db:/data/configdb
    networks:
      - internal_network

  amor-segb-neo4j:
    container_name: amor-segb-neo4j
    image: neo4j:5.20.0
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/neoforyou
      - NEO4J_PLUGINS=["apoc", "n10s"]

    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge

volumes:
  amor-segb-db:
  neo4j_data: # Do not use same volume for mongo and neo4j
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
