services:
  amor-segb:
    container_name: amor-segb-server
    image: ghcr.io/gsi-upm/amor-segb:0.4.1
    build: .
    ports:
      - "5000:5000"
    networks:
      - internal_network
    depends_on:
      - amor-segb-mongodb
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_SERVICE=amor-segb-mongodb
      - LOGGING_LEVEL=DEBUG
    volumes:
      - ./logs:/logs

  amor-segb-mongodb:
    container_name: amor-segb-mongodb
    image: mongodb/mongodb-community-server:8.0.0-ubi8
    volumes:
      - amor-segb-db:/data/db
      - amor-segb-db:/data/configdb
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge

volumes:
  amor-segb-db: