FROM python:3.12-slim-bookworm

COPY --from=ghcr.io/astral-sh/uv:0.6.12 /uv /uvx /bin/

WORKDIR /app

# Instala dependencias
ADD pyproject.toml uv.lock ./
RUN uv sync --frozen

# Copia el código de frontend
COPY ./server /app
ENV PYTHONPATH=/app

EXPOSE 8501

# Ejecuta streamlit desde el entorno virtual
CMD ["uv", "run", "streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]