services:
  segb:
    container_name: segb-server
    image: ghcr.io/gsi-upm/segb:0.4.6
    build: .
    ports:
      - "5000:5000"
    networks:
      - internal_network
    depends_on:
      - segb-mongodb
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_SERVICE=segb-mongodb
      - LOGGING_LEVEL=DEBUG
    volumes:
      - ./logs:/logs
      # If you want to modify the logging configuration, you can mount this file.
      # The application reads this file at startup using the PyYAML library.

      # - ./log_conf.yaml:/app/log_conf.yaml

  segb-mongodb:
    container_name: segb-mongodb
    image: mongodb/mongodb-community-server:8.0.0-ubi8
    volumes:
      - segb-db:/data/db
      - segb-db:/data/configdb
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge

volumes:
  segb-db: