services:
  amor-segb:
    container_name: amor-segb-server
    image: ghcr.io/gsi-upm/amor-segb:0.4.5
    build: .
    ports:
      - "5000:5000"
    networks:
      - internal_network
    depends_on:
      - amor-segb-mongodb
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_SERVICE=amor-segb-mongodb
      - LOGGING_LEVEL=DEBUG
    # volumes:
      # If you want to modify the logging configuration, you can mount this file.
      # The application reads this file at startup using the PyYAML library.

      # - ./log_conf.yaml:/app/log_conf.yaml

  amor-segb-mongodb:
    container_name: amor-segb-mongodb
    image: mongodb/mongodb-community-server:8.0.0-ubi8
    volumes:
      - amor-segb-db:/data/db
      - amor-segb-db:/data/configdb
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge

volumes:
  amor-segb-db: