PREFIX oro: <http://kb.openrobots.org#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX segb: <http://www.gsi.upm.es/ontologies/segb/ns#>

SELECT ?initialActivity ?listenMsgContent 
        ?resultingActivity ?responseMsgContent
        ?robot ?human
WHERE {
?activity a segb:LoggedActivity ;
    segb:triggeredByActivity ?initialActivity ;
    segb:producedActivityResult ?resultingActivity ;
    prov:wasAssociatedWith ?robot .
?resultingActivity a oro:SpeechAction ;
    prov:wasAssociatedWith ?robot .
?initialActivity a oro:ListeningEvent ;
    oro:hasSpeaker ?human ;
    prov:wasAssociatedWith ?robot .
?listenMsg a oro:Message ;
    prov:wasGeneratedBy ?initialActivity ;
    oro:hasValue ?listenMsgContent .
?responseMsg a oro:Message ;
    prov:wasGeneratedBy ?resultActivity ;
    oro:hasValue ?responseMsgContent .
}